-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgNapzmNdNOqESlSLK
zH5cRgbB+uaTEftTUiTKs3TalACgCgYIKoZIzj0DAQehRANCAASSB2GcWV9QI6Dy
zUWW+HuZSQJXjz1W/g7p/XLajIddE6QXa0Y6cpOo+L8wH9z/kYMq0TMN4UMPVgQ8
6J7PZlhW
-----END PRIVATE KEY-----