#!/bin/bash
# PRODUCTION DEPLOYMENT COMMANDS
# Copy and paste these commands to deploy to Hostinger VPS

echo "═══════════════════════════════════════════════════════════"
echo "  🚀 Tidyupsbooking.com - Production Deployment"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Repository Status: ✅ READY FOR DEPLOYMENT"
echo "Branch: emergent-updates"
echo "Last Commit: $(git log -1 --format='%h - %s')"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 1: SSH into your Hostinger VPS"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Run on your local machine:"
echo ""
echo "  ssh user@your-vps-ip"
echo ""
echo "Replace 'user' and 'your-vps-ip' with your actual credentials"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 2: Clone repository (FIRST TIME ONLY)"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Run on VPS (skip if already cloned):"
echo ""
echo "  git clone https://github.com/tidyups-booking/Tidyups-Book-Scrubby.git"
echo "  cd Tidyups-Book-Scrubby"
echo "  git checkout emergent-updates"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 3: Update to latest code (IF ALREADY DEPLOYED)"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Run on VPS (skip if first deployment):"
echo ""
echo "  cd ~/Tidyups-Book-Scrubby"
echo "  git pull origin emergent-updates"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 4: Navigate to deployment directory"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Run on VPS:"
echo ""
echo "  cd ~/Tidyups-Book-Scrubby/deploy/hostinger"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 5: Run pre-deployment verification"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Run on VPS:"
echo ""
echo "  ./verify.sh"
echo ""
echo "This will check all prerequisites are met."
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 6: Configure environment (FIRST TIME ONLY)"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Run on VPS (skip if .env already configured):"
echo ""
echo "  cp .env.example .env"
echo "  nano .env"
echo ""
echo "Set ADMIN_PASSWORD to a strong password, then save (Ctrl+X, Y, Enter)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 7: DEPLOY! 🚀"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Run on VPS:"
echo ""
echo "  ./deploy.sh"
echo ""
echo "This will build and start all services."
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 8: Monitor deployment"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Run on VPS to watch logs:"
echo ""
echo "  docker compose logs -f"
echo ""
echo "Press Ctrl+C to stop watching logs (services keep running)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 9: Verify deployment"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Check service status on VPS:"
echo ""
echo "  docker compose ps"
echo ""
echo "All services should show 'Up' or 'Up (healthy)'"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 10: Test in browser"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Wait 2-3 minutes for HTTPS certificates, then visit:"
echo ""
echo "  ✓ Frontend:  https://tidyupsbooking.com"
echo "  ✓ API:       https://api.tidyupsbooking.com/api/"
echo "  ✓ Portainer: https://manage.tidyupsbooking.com"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📚 Documentation:"
echo ""
echo "  • Quick guide:      deploy/hostinger/DEPLOY.md"
echo "  • Full checklist:   DEPLOYMENT_CHECKLIST.md"
echo "  • Status document:  PRODUCTION_STATUS.md"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🆘 Troubleshooting:"
echo ""
echo "  View API logs:     docker compose logs -f api"
echo "  View Caddy logs:   docker compose logs -f caddy"
echo "  Restart service:   docker compose restart api"
echo "  Full restart:      docker compose down && docker compose up -d"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✅ Repository is ready! Follow the steps above to deploy."
echo ""
